<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="2" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-12-15T14:31:46 IST" name="Suite" finished-at="2023-12-15T14:32:41 IST" duration-ms="55008">
    <groups>
    </groups>
    <test started-at="2023-12-15T14:31:46 IST" name="Test" finished-at="2023-12-15T14:32:41 IST" duration-ms="55008">
      <class name="Testng.ActitimeRunnerscript">
        <test-method is-config="true" signature="openapp()[pri:0, instance:Testng.ActitimeRunnerscript@be35cd9]" started-at="2023-12-15T14:31:46 IST" name="openapp" finished-at="2023-12-15T14:31:53 IST" duration-ms="7381" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openapp -->
        <test-method signature="validLogin()[pri:0, instance:Testng.ActitimeRunnerscript@be35cd9]" started-at="2023-12-15T14:31:53 IST" name="validLogin" finished-at="2023-12-15T14:31:59 IST" duration-ms="5656" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Faceboook] but found [Log in to Facebook]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Faceboook] but found [Log in to Facebook]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at Testng.ActitimeRunnerscript.validLogin(ActitimeRunnerscript.java:18)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLogin -->
        <test-method is-config="true" signature="closeapp()[pri:0, instance:Testng.ActitimeRunnerscript@be35cd9]" started-at="2023-12-15T14:31:59 IST" name="closeapp" finished-at="2023-12-15T14:32:01 IST" duration-ms="1779" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeapp -->
        <test-method is-config="true" signature="openapp()[pri:0, instance:Testng.ActitimeRunnerscript@be35cd9]" started-at="2023-12-15T14:32:01 IST" name="openapp" finished-at="2023-12-15T14:32:07 IST" duration-ms="5936" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openapp -->
        <test-method signature="validLogin1()[pri:0, instance:Testng.ActitimeRunnerscript@be35cd9]" started-at="2023-12-15T14:32:07 IST" name="validLogin1" finished-at="2023-12-15T14:32:12 IST" duration-ms="5663" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLogin1 -->
        <test-method is-config="true" signature="closeapp()[pri:0, instance:Testng.ActitimeRunnerscript@be35cd9]" started-at="2023-12-15T14:32:12 IST" name="closeapp" finished-at="2023-12-15T14:32:14 IST" duration-ms="2023" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeapp -->
      </class> <!-- Testng.ActitimeRunnerscript -->
      <class name="Testng.Facebook">
        <test-method is-config="true" signature="openapp()[pri:0, instance:Testng.Facebook@3d5c822d]" started-at="2023-12-15T14:32:14 IST" name="openapp" finished-at="2023-12-15T14:32:20 IST" duration-ms="6072" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openapp -->
        <test-method signature="validLogin()[pri:0, instance:Testng.Facebook@3d5c822d]" started-at="2023-12-15T14:32:20 IST" name="validLogin" finished-at="2023-12-15T14:32:26 IST" duration-ms="5357" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Faceboook] but found [Log in to Facebook]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Faceboook] but found [Log in to Facebook]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at Testng.Facebook.validLogin(Facebook.java:20)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLogin -->
        <test-method is-config="true" signature="closeapp()[pri:0, instance:Testng.Facebook@3d5c822d]" started-at="2023-12-15T14:32:26 IST" name="closeapp" finished-at="2023-12-15T14:32:28 IST" duration-ms="1817" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeapp -->
        <test-method is-config="true" signature="openapp()[pri:0, instance:Testng.Facebook@3d5c822d]" started-at="2023-12-15T14:32:28 IST" name="openapp" finished-at="2023-12-15T14:32:33 IST" duration-ms="5521" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openapp -->
        <test-method signature="validLogin1()[pri:0, instance:Testng.Facebook@3d5c822d]" started-at="2023-12-15T14:32:33 IST" name="validLogin1" finished-at="2023-12-15T14:32:39 IST" duration-ms="5704" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLogin1 -->
        <test-method is-config="true" signature="closeapp()[pri:0, instance:Testng.Facebook@3d5c822d]" started-at="2023-12-15T14:32:39 IST" name="closeapp" finished-at="2023-12-15T14:32:41 IST" duration-ms="2002" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeapp -->
      </class> <!-- Testng.Facebook -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
